export interface GeneratedCheckResult {
  isGenerated: boolean;
  reason?: string;
}

const exactFilenames = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lock",
  "bun.lockb",
  "Cargo.lock",
  "Gemfile.lock",
  "go.sum",
  "go.mod",
  "poetry.lock",
  "uv.lock",
  "pdm.lock",
  "composer.lock",
  "pubspec.lock",
  "flake.lock",
  "Package.resolved",
  ".terraform.lock.hcl",
]);

const generatedSuffixes = [
  ".min.js",
  ".min.css",
  ".map",
  ".pb.go",
  ".pb.rb",
  ".pb.py",
  ".pb.js",
  ".pb.cc",
  ".pb.h",
  ".grpc.pb.go",
  ".graphql.ts",
  ".graphql.js",
  ".openapi.ts",
  ".openapi.js",
  ".msw.ts",
  ".zod.ts",
  ".api.ts",
  ".g.dart",
  ".freezed.dart",
  ".g.cs",
  ".designer.cs",
  "_ide_helper.php",
];

const generatedPathParts = ["/generated/", "/gen/", "/__generated__/"];
const rootGeneratedPrefixes = ["vendor/", "node_modules/", "dist/", "build/", "out/"];

const generatedHeaderPatterns = [
  /@generated\b/,
  /\bDO NOT EDIT\b/i,
  /\bDO NOT MODIFY\b/i,
  /\bAUTO[- ]?GENERATED\b/i,
  /\bTHIS FILE IS GENERATED\b/i,
  /\bGENERATED CODE\b/i,
  /\bMACHINE GENERATED\b/i,
  /Generated by\b/i,
  /Autogenerated by\b/i,
  /This file was generated/i,
  /<auto-generated\s*\/?>/i,
  /Generated by graphql-codegen/i,
  /Generated by orval/i,
  /Prisma Client JS/i,
  /Generated by the protocol buffer/i,
];

export function checkGeneratedFile(path: string, headerLines: string[] = []): GeneratedCheckResult {
  const normalizedPath = path.replaceAll("\\", "/");
  const fileName = normalizedPath.split("/").pop() ?? normalizedPath;
  if (exactFilenames.has(fileName)) return { isGenerated: true, reason: "lockfile" };
  if (generatedSuffixes.some((suffix) => fileName.endsWith(suffix))) {
    return { isGenerated: true, reason: "generated suffix" };
  }
  if (/\.(generated|gen)\.[A-Za-z0-9]+$/.test(fileName)) {
    return { isGenerated: true, reason: "generated filename" };
  }
  if (rootGeneratedPrefixes.some((prefix) => normalizedPath.startsWith(prefix))) {
    return { isGenerated: true, reason: "generated directory" };
  }
  if (generatedPathParts.some((part) => normalizedPath.includes(part))) {
    return { isGenerated: true, reason: "generated directory" };
  }
  if (/\.(md|markdown)$/i.test(fileName)) return { isGenerated: false };

  const header = headerLines.slice(0, 20).join("\n");
  const matchedHeader = generatedHeaderPatterns.find((pattern) => pattern.test(header));
  if (matchedHeader) return { isGenerated: true, reason: matchedHeader.source };
  return { isGenerated: false };
}
